export const userActionTypes = {
  SETUP_USER_BEGIN: 'SETUP_USER_BEGIN ',
  SETUP_USER_SUCCESS: 'SETUP_USER_SUCCESS ',
  SETUP_USER_ERROR: 'SETUP_USER_ERROR ',
  UPDATE_ONLINE: 'UPDATE_ONLINE',
  SETUP_SOCKET_STATUS: 'SETUP_SOCKET_STATUS',
  SET_CURRENT_ACTION: 'SET_CURRENT_ACTION',

  // Crypto
  SETUP_CRYPTO_BEGIN: 'SETUP_CRYPTO_BEGIN ',
  SETUP_CRYPTO_SUCCESS: 'SETUP_CRYPTO_SUCCESS ',
  SETUP_CRYPTO_ERROR: 'SETUP_CRYPTO_ERROR ',
  CLEAR_CRYPTO_STATUS: 'CLEAR_CRYPTO_STATUS',
};

export const egmActionTypes = {
  // Get Egm List
  SETUP_EGM_LIST_BEGIN: 'SETUP_EGM_LIST_BEGIN ',
  SETUP_EGM_LIST_SUCCESS: 'SETUP_EGM_LIST_SUCCESS ',
  SETUP_EGM_LIST_ERROR: 'SETUP_EGM_LIST_ERROR ',
  CLEAR_EGM_LIST_STATUS: 'CLEAR_EGM_LIST_STATUS',

  LEAVE_EGM_BEGIN: 'LEAVE_EGM_BEGIN',
  LEAVE_EGM_SUCCESS: 'LEAVE_EGM_SUCCESS',
  LEAVE_EGM_ERROR: 'LEAVE_EGM_ERROR',
  LEAVE_EGM_CLEAR: 'LEAVE_EGM_CLEAR',

  UPDATE_EGM: 'UPDATE_EGM',

  // Egm Status
  IS_PLAYING: 'IS_PLAYING',

  // Get Brand List
  SETUP_BRAND_LIST_BEGIN: 'SETUP_BRAND_LIST_BEGIN ',
  SETUP_BRAND_LIST_SUCCESS: 'SETUP_BRAND_LIST_SUCCESS ',
  SETUP_BRAND_LIST_ERROR: 'SETUP_BRAND_LIST_ERROR ',
  CLEAR_BRAND_LIST_STATUS: 'CLEAR_BRAND_LIST_STATUS',

  // Select Egm
  SETUP_SELECT_EGM_BEGIN: 'SETUP_SELECT_EGM_BEGIN ',
  SETUP_SELECT_EGM_SUCCESS: 'SETUP_SELECT_EGM_SUCCESS ',
  SETUP_SELECT_EGM_ERROR: 'SETUP_SELECT_EGM_ERROR ',
  SETUP_CURRENT_BTN_PRESS: 'SETUP_CURRENT_BTN_PRESS',
  CLEAR_SELECT_EGM_DATA: 'CLEAR_SELECT_EGM_DATA',

  // Button Press
  BUTTON_PRESS_BEGIN: 'BUTTON_PRESS_BEGIN',
  BUTTON_PRESS_SUCCESS: 'BUTTON_PRESS_SUCCESS',
  BUTTON_PRESS_ERROR: 'BUTTON_PRESS_ERROR',
  CLEAR_BUTTON_PRESS_STATUS: 'CLEAR_BUTTON_PRESS_STATUS',

  // Cash in Out
  CASH_IN_OUT_BEGIN: 'CASH_IN_OUT_BEGIN',
  CASH_IN_OUT_SUCCESS: 'CASH_IN_OUT_SUCCESS',
  CASH_IN_OUT_ERROR: 'CASH_IN_OUT_ERROR',
  CLEAR_CASH_IN_OUT_STATUS: 'CLEAR_CASH_IN_OUT_STATUS',

  // Set Cash in out Form
  SET_AFT_FORM: 'SET_AFT_FORM',
  CLEAR_AFT_FORM: 'CLEAR_AFT_FORM',

  //bookinList
  BOOKING_LIST_SUCCESS: 'BOOKING_LIST_SUCCESS',
  BOOKING_LIST_ERROR: 'BOOKING_LIST_ERROR',
};

export const pixiActionTypes = {
  STATUS_ON: 'STATUS_ON',
  STATUS_OFF: 'STATUS_OFF',
};

export const menuActionTypes = {
  SET_CURRENT_MENU: 'SET_CURRENT_MENU',
};

export const rootActionTypes = {
  RESET_STORE: 'RESET_STORE',
};

export const chatActionTypes = {
  SET_MESSAGE_LIST: 'SET_MESSAGE_LIST',
};

export const japanSlotActionsTypes = {
  SET_POINT: 'SET_POINT',
  CLEAN_STATUS: 'CLEAN_STATUS',
};

export const cashInActionTypes = {
  CASH_IN_BEGIN: '[Cash In]: Cash_IN_BEGIN',
  CASH_IN_SUCCESS: '[Cash In]: CASH_IN_SUCCESS ',
  CASH_IN_ERROR: '[Cash In]: CASH_IN_ERROR ',
};
